STOCK_MARKET_OPEN_TIME = "09:30"
STOCK_MARKET_CLOSE_TIME = "16:55"
MAX_STOP_LOSS_PERCENT = 0.07
STOCK_SCANNER_PARTITION_COUNT = 40
STOCKS_TO_CHECK = ["AAPL", "AMD", "TSLA", "FB", "MSFT", "F", "GME", "QCOM", "AMZN", "GOOG", "SPCE", "BMBL", "LYFT"]
ARTICLE_MIN_COUNT_NEWS = 10 # needs ARTICLE_MIN_COUNT_NEWS articles or more to buy stocks based on news classifier
